/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yohpapa_research_searchsample_ShortnameHelper */

#ifndef _Included_com_yohpapa_research_searchsample_ShortnameHelper
#define _Included_com_yohpapa_research_searchsample_ShortnameHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yohpapa_research_searchsample_ShortnameHelper
 * Method:    GetShortName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_yohpapa_research_searchsample_ShortnameHelper_GetShortName
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
