/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yohpapa_research_actionbar_FileListGenerator_FileItem */

#ifndef _Included_com_yohpapa_research_actionbar_FileListGenerator_FileItem
#define _Included_com_yohpapa_research_actionbar_FileListGenerator_FileItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yohpapa_research_actionbar_FileListGenerator_FileItem
 * Method:    GetShortName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_yohpapa_research_actionbar_FileListGenerator_00024FileItem_GetShortName
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
